// Generated by gencpp from file lorett_c4s/Execute.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_EXECUTE_H
#define LORETT_C4S_MESSAGE_EXECUTE_H

#include <ros/service_traits.h>


#include <lorett_c4s/ExecuteRequest.h>
#include <lorett_c4s/ExecuteResponse.h>


namespace lorett_c4s
{

struct Execute
{

typedef ExecuteRequest Request;
typedef ExecuteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Execute
} // namespace lorett_c4s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lorett_c4s::Execute > {
  static const char* value()
  {
    return "39a6fda3761b984206ead71aea9c2751";
  }

  static const char* value(const ::lorett_c4s::Execute&) { return value(); }
};

template<>
struct DataType< ::lorett_c4s::Execute > {
  static const char* value()
  {
    return "lorett_c4s/Execute";
  }

  static const char* value(const ::lorett_c4s::Execute&) { return value(); }
};


// service_traits::MD5Sum< ::lorett_c4s::ExecuteRequest> should match
// service_traits::MD5Sum< ::lorett_c4s::Execute >
template<>
struct MD5Sum< ::lorett_c4s::ExecuteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::Execute >::value();
  }
  static const char* value(const ::lorett_c4s::ExecuteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::ExecuteRequest> should match
// service_traits::DataType< ::lorett_c4s::Execute >
template<>
struct DataType< ::lorett_c4s::ExecuteRequest>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::Execute >::value();
  }
  static const char* value(const ::lorett_c4s::ExecuteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lorett_c4s::ExecuteResponse> should match
// service_traits::MD5Sum< ::lorett_c4s::Execute >
template<>
struct MD5Sum< ::lorett_c4s::ExecuteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::Execute >::value();
  }
  static const char* value(const ::lorett_c4s::ExecuteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::ExecuteResponse> should match
// service_traits::DataType< ::lorett_c4s::Execute >
template<>
struct DataType< ::lorett_c4s::ExecuteResponse>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::Execute >::value();
  }
  static const char* value(const ::lorett_c4s::ExecuteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LORETT_C4S_MESSAGE_EXECUTE_H
