// Generated by gencpp from file lorett_c4s/Navigate.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_NAVIGATE_H
#define LORETT_C4S_MESSAGE_NAVIGATE_H

#include <ros/service_traits.h>


#include <lorett_c4s/NavigateRequest.h>
#include <lorett_c4s/NavigateResponse.h>


namespace lorett_c4s
{

struct Navigate
{

typedef NavigateRequest Request;
typedef NavigateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Navigate
} // namespace lorett_c4s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lorett_c4s::Navigate > {
  static const char* value()
  {
    return "d27cf8a87020c28b3d14e06881a86c21";
  }

  static const char* value(const ::lorett_c4s::Navigate&) { return value(); }
};

template<>
struct DataType< ::lorett_c4s::Navigate > {
  static const char* value()
  {
    return "lorett_c4s/Navigate";
  }

  static const char* value(const ::lorett_c4s::Navigate&) { return value(); }
};


// service_traits::MD5Sum< ::lorett_c4s::NavigateRequest> should match
// service_traits::MD5Sum< ::lorett_c4s::Navigate >
template<>
struct MD5Sum< ::lorett_c4s::NavigateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::Navigate >::value();
  }
  static const char* value(const ::lorett_c4s::NavigateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::NavigateRequest> should match
// service_traits::DataType< ::lorett_c4s::Navigate >
template<>
struct DataType< ::lorett_c4s::NavigateRequest>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::Navigate >::value();
  }
  static const char* value(const ::lorett_c4s::NavigateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lorett_c4s::NavigateResponse> should match
// service_traits::MD5Sum< ::lorett_c4s::Navigate >
template<>
struct MD5Sum< ::lorett_c4s::NavigateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::Navigate >::value();
  }
  static const char* value(const ::lorett_c4s::NavigateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::NavigateResponse> should match
// service_traits::DataType< ::lorett_c4s::Navigate >
template<>
struct DataType< ::lorett_c4s::NavigateResponse>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::Navigate >::value();
  }
  static const char* value(const ::lorett_c4s::NavigateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LORETT_C4S_MESSAGE_NAVIGATE_H
