// Generated by gencpp from file lorett_c4s/yawPose.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_YAWPOSE_H
#define LORETT_C4S_MESSAGE_YAWPOSE_H

#include <ros/service_traits.h>


#include <lorett_c4s/yawPoseRequest.h>
#include <lorett_c4s/yawPoseResponse.h>


namespace lorett_c4s
{

struct yawPose
{

typedef yawPoseRequest Request;
typedef yawPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct yawPose
} // namespace lorett_c4s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lorett_c4s::yawPose > {
  static const char* value()
  {
    return "f68e4433a4689785cdd462b8b218a593";
  }

  static const char* value(const ::lorett_c4s::yawPose&) { return value(); }
};

template<>
struct DataType< ::lorett_c4s::yawPose > {
  static const char* value()
  {
    return "lorett_c4s/yawPose";
  }

  static const char* value(const ::lorett_c4s::yawPose&) { return value(); }
};


// service_traits::MD5Sum< ::lorett_c4s::yawPoseRequest> should match
// service_traits::MD5Sum< ::lorett_c4s::yawPose >
template<>
struct MD5Sum< ::lorett_c4s::yawPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::yawPose >::value();
  }
  static const char* value(const ::lorett_c4s::yawPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::yawPoseRequest> should match
// service_traits::DataType< ::lorett_c4s::yawPose >
template<>
struct DataType< ::lorett_c4s::yawPoseRequest>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::yawPose >::value();
  }
  static const char* value(const ::lorett_c4s::yawPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lorett_c4s::yawPoseResponse> should match
// service_traits::MD5Sum< ::lorett_c4s::yawPose >
template<>
struct MD5Sum< ::lorett_c4s::yawPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::yawPose >::value();
  }
  static const char* value(const ::lorett_c4s::yawPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::yawPoseResponse> should match
// service_traits::DataType< ::lorett_c4s::yawPose >
template<>
struct DataType< ::lorett_c4s::yawPoseResponse>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::yawPose >::value();
  }
  static const char* value(const ::lorett_c4s::yawPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LORETT_C4S_MESSAGE_YAWPOSE_H
