// Generated by gencpp from file lorett_c4s/NavigateGlobal.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_NAVIGATEGLOBAL_H
#define LORETT_C4S_MESSAGE_NAVIGATEGLOBAL_H

#include <ros/service_traits.h>


#include <lorett_c4s/NavigateGlobalRequest.h>
#include <lorett_c4s/NavigateGlobalResponse.h>


namespace lorett_c4s
{

struct NavigateGlobal
{

typedef NavigateGlobalRequest Request;
typedef NavigateGlobalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavigateGlobal
} // namespace lorett_c4s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lorett_c4s::NavigateGlobal > {
  static const char* value()
  {
    return "fd9375a2b183ad5a1c80cf671893464b";
  }

  static const char* value(const ::lorett_c4s::NavigateGlobal&) { return value(); }
};

template<>
struct DataType< ::lorett_c4s::NavigateGlobal > {
  static const char* value()
  {
    return "lorett_c4s/NavigateGlobal";
  }

  static const char* value(const ::lorett_c4s::NavigateGlobal&) { return value(); }
};


// service_traits::MD5Sum< ::lorett_c4s::NavigateGlobalRequest> should match
// service_traits::MD5Sum< ::lorett_c4s::NavigateGlobal >
template<>
struct MD5Sum< ::lorett_c4s::NavigateGlobalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::NavigateGlobal >::value();
  }
  static const char* value(const ::lorett_c4s::NavigateGlobalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::NavigateGlobalRequest> should match
// service_traits::DataType< ::lorett_c4s::NavigateGlobal >
template<>
struct DataType< ::lorett_c4s::NavigateGlobalRequest>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::NavigateGlobal >::value();
  }
  static const char* value(const ::lorett_c4s::NavigateGlobalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lorett_c4s::NavigateGlobalResponse> should match
// service_traits::MD5Sum< ::lorett_c4s::NavigateGlobal >
template<>
struct MD5Sum< ::lorett_c4s::NavigateGlobalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::NavigateGlobal >::value();
  }
  static const char* value(const ::lorett_c4s::NavigateGlobalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::NavigateGlobalResponse> should match
// service_traits::DataType< ::lorett_c4s::NavigateGlobal >
template<>
struct DataType< ::lorett_c4s::NavigateGlobalResponse>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::NavigateGlobal >::value();
  }
  static const char* value(const ::lorett_c4s::NavigateGlobalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LORETT_C4S_MESSAGE_NAVIGATEGLOBAL_H
