// Generated by gencpp from file lorett_c4s/publishPoseResponse.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_PUBLISHPOSERESPONSE_H
#define LORETT_C4S_MESSAGE_PUBLISHPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lorett_c4s
{
template <class ContainerAllocator>
struct publishPoseResponse_
{
  typedef publishPoseResponse_<ContainerAllocator> Type;

  publishPoseResponse_()
    : s(false)  {
    }
  publishPoseResponse_(const ContainerAllocator& _alloc)
    : s(false)  {
  (void)_alloc;
    }



   typedef uint8_t _s_type;
  _s_type s;





  typedef boost::shared_ptr< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct publishPoseResponse_

typedef ::lorett_c4s::publishPoseResponse_<std::allocator<void> > publishPoseResponse;

typedef boost::shared_ptr< ::lorett_c4s::publishPoseResponse > publishPoseResponsePtr;
typedef boost::shared_ptr< ::lorett_c4s::publishPoseResponse const> publishPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lorett_c4s::publishPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lorett_c4s::publishPoseResponse_<ContainerAllocator1> & lhs, const ::lorett_c4s::publishPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lorett_c4s::publishPoseResponse_<ContainerAllocator1> & lhs, const ::lorett_c4s::publishPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lorett_c4s

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d9ddd4827722ec078b0a4ab6e9e75d4";
  }

  static const char* value(const ::lorett_c4s::publishPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d9ddd4827722ec0ULL;
  static const uint64_t static_value2 = 0x78b0a4ab6e9e75d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lorett_c4s/publishPoseResponse";
  }

  static const char* value(const ::lorett_c4s::publishPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool s\n"
;
  }

  static const char* value(const ::lorett_c4s::publishPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct publishPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lorett_c4s::publishPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lorett_c4s::publishPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LORETT_C4S_MESSAGE_PUBLISHPOSERESPONSE_H
