// Generated by gencpp from file lorett_c4s/publishPose.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_PUBLISHPOSE_H
#define LORETT_C4S_MESSAGE_PUBLISHPOSE_H

#include <ros/service_traits.h>


#include <lorett_c4s/publishPoseRequest.h>
#include <lorett_c4s/publishPoseResponse.h>


namespace lorett_c4s
{

struct publishPose
{

typedef publishPoseRequest Request;
typedef publishPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct publishPose
} // namespace lorett_c4s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lorett_c4s::publishPose > {
  static const char* value()
  {
    return "03060af12faad2362b583a9f05054681";
  }

  static const char* value(const ::lorett_c4s::publishPose&) { return value(); }
};

template<>
struct DataType< ::lorett_c4s::publishPose > {
  static const char* value()
  {
    return "lorett_c4s/publishPose";
  }

  static const char* value(const ::lorett_c4s::publishPose&) { return value(); }
};


// service_traits::MD5Sum< ::lorett_c4s::publishPoseRequest> should match
// service_traits::MD5Sum< ::lorett_c4s::publishPose >
template<>
struct MD5Sum< ::lorett_c4s::publishPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::publishPose >::value();
  }
  static const char* value(const ::lorett_c4s::publishPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::publishPoseRequest> should match
// service_traits::DataType< ::lorett_c4s::publishPose >
template<>
struct DataType< ::lorett_c4s::publishPoseRequest>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::publishPose >::value();
  }
  static const char* value(const ::lorett_c4s::publishPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lorett_c4s::publishPoseResponse> should match
// service_traits::MD5Sum< ::lorett_c4s::publishPose >
template<>
struct MD5Sum< ::lorett_c4s::publishPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::publishPose >::value();
  }
  static const char* value(const ::lorett_c4s::publishPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::publishPoseResponse> should match
// service_traits::DataType< ::lorett_c4s::publishPose >
template<>
struct DataType< ::lorett_c4s::publishPoseResponse>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::publishPose >::value();
  }
  static const char* value(const ::lorett_c4s::publishPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LORETT_C4S_MESSAGE_PUBLISHPOSE_H
