// Generated by gencpp from file lorett_c4s/SetAttitude.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_SETATTITUDE_H
#define LORETT_C4S_MESSAGE_SETATTITUDE_H

#include <ros/service_traits.h>


#include <lorett_c4s/SetAttitudeRequest.h>
#include <lorett_c4s/SetAttitudeResponse.h>


namespace lorett_c4s
{

struct SetAttitude
{

typedef SetAttitudeRequest Request;
typedef SetAttitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAttitude
} // namespace lorett_c4s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lorett_c4s::SetAttitude > {
  static const char* value()
  {
    return "cc2080a08d58c004756f050a7b2dc084";
  }

  static const char* value(const ::lorett_c4s::SetAttitude&) { return value(); }
};

template<>
struct DataType< ::lorett_c4s::SetAttitude > {
  static const char* value()
  {
    return "lorett_c4s/SetAttitude";
  }

  static const char* value(const ::lorett_c4s::SetAttitude&) { return value(); }
};


// service_traits::MD5Sum< ::lorett_c4s::SetAttitudeRequest> should match
// service_traits::MD5Sum< ::lorett_c4s::SetAttitude >
template<>
struct MD5Sum< ::lorett_c4s::SetAttitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::SetAttitude >::value();
  }
  static const char* value(const ::lorett_c4s::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::SetAttitudeRequest> should match
// service_traits::DataType< ::lorett_c4s::SetAttitude >
template<>
struct DataType< ::lorett_c4s::SetAttitudeRequest>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::SetAttitude >::value();
  }
  static const char* value(const ::lorett_c4s::SetAttitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lorett_c4s::SetAttitudeResponse> should match
// service_traits::MD5Sum< ::lorett_c4s::SetAttitude >
template<>
struct MD5Sum< ::lorett_c4s::SetAttitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::SetAttitude >::value();
  }
  static const char* value(const ::lorett_c4s::SetAttitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::SetAttitudeResponse> should match
// service_traits::DataType< ::lorett_c4s::SetAttitude >
template<>
struct DataType< ::lorett_c4s::SetAttitudeResponse>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::SetAttitude >::value();
  }
  static const char* value(const ::lorett_c4s::SetAttitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LORETT_C4S_MESSAGE_SETATTITUDE_H
