// Generated by gencpp from file lorett_c4s/SetLEDEffect.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_SETLEDEFFECT_H
#define LORETT_C4S_MESSAGE_SETLEDEFFECT_H

#include <ros/service_traits.h>


#include <lorett_c4s/SetLEDEffectRequest.h>
#include <lorett_c4s/SetLEDEffectResponse.h>


namespace lorett_c4s
{

struct SetLEDEffect
{

typedef SetLEDEffectRequest Request;
typedef SetLEDEffectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLEDEffect
} // namespace lorett_c4s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lorett_c4s::SetLEDEffect > {
  static const char* value()
  {
    return "044f75c927403b22bd59e8dbf871eabd";
  }

  static const char* value(const ::lorett_c4s::SetLEDEffect&) { return value(); }
};

template<>
struct DataType< ::lorett_c4s::SetLEDEffect > {
  static const char* value()
  {
    return "lorett_c4s/SetLEDEffect";
  }

  static const char* value(const ::lorett_c4s::SetLEDEffect&) { return value(); }
};


// service_traits::MD5Sum< ::lorett_c4s::SetLEDEffectRequest> should match
// service_traits::MD5Sum< ::lorett_c4s::SetLEDEffect >
template<>
struct MD5Sum< ::lorett_c4s::SetLEDEffectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::SetLEDEffect >::value();
  }
  static const char* value(const ::lorett_c4s::SetLEDEffectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::SetLEDEffectRequest> should match
// service_traits::DataType< ::lorett_c4s::SetLEDEffect >
template<>
struct DataType< ::lorett_c4s::SetLEDEffectRequest>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::SetLEDEffect >::value();
  }
  static const char* value(const ::lorett_c4s::SetLEDEffectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lorett_c4s::SetLEDEffectResponse> should match
// service_traits::MD5Sum< ::lorett_c4s::SetLEDEffect >
template<>
struct MD5Sum< ::lorett_c4s::SetLEDEffectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::SetLEDEffect >::value();
  }
  static const char* value(const ::lorett_c4s::SetLEDEffectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::SetLEDEffectResponse> should match
// service_traits::DataType< ::lorett_c4s::SetLEDEffect >
template<>
struct DataType< ::lorett_c4s::SetLEDEffectResponse>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::SetLEDEffect >::value();
  }
  static const char* value(const ::lorett_c4s::SetLEDEffectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LORETT_C4S_MESSAGE_SETLEDEFFECT_H
