// Generated by gencpp from file lorett_c4s/SetPosition.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_SETPOSITION_H
#define LORETT_C4S_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <lorett_c4s/SetPositionRequest.h>
#include <lorett_c4s/SetPositionResponse.h>


namespace lorett_c4s
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace lorett_c4s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lorett_c4s::SetPosition > {
  static const char* value()
  {
    return "69cb8e201b1f4163f507e2b13fa97684";
  }

  static const char* value(const ::lorett_c4s::SetPosition&) { return value(); }
};

template<>
struct DataType< ::lorett_c4s::SetPosition > {
  static const char* value()
  {
    return "lorett_c4s/SetPosition";
  }

  static const char* value(const ::lorett_c4s::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::lorett_c4s::SetPositionRequest> should match
// service_traits::MD5Sum< ::lorett_c4s::SetPosition >
template<>
struct MD5Sum< ::lorett_c4s::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::SetPosition >::value();
  }
  static const char* value(const ::lorett_c4s::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::SetPositionRequest> should match
// service_traits::DataType< ::lorett_c4s::SetPosition >
template<>
struct DataType< ::lorett_c4s::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::SetPosition >::value();
  }
  static const char* value(const ::lorett_c4s::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lorett_c4s::SetPositionResponse> should match
// service_traits::MD5Sum< ::lorett_c4s::SetPosition >
template<>
struct MD5Sum< ::lorett_c4s::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::SetPosition >::value();
  }
  static const char* value(const ::lorett_c4s::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::SetPositionResponse> should match
// service_traits::DataType< ::lorett_c4s::SetPosition >
template<>
struct DataType< ::lorett_c4s::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::SetPosition >::value();
  }
  static const char* value(const ::lorett_c4s::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LORETT_C4S_MESSAGE_SETPOSITION_H
