// Generated by gencpp from file lorett_c4s/SetRatesRequest.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_SETRATESREQUEST_H
#define LORETT_C4S_MESSAGE_SETRATESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lorett_c4s
{
template <class ContainerAllocator>
struct SetRatesRequest_
{
  typedef SetRatesRequest_<ContainerAllocator> Type;

  SetRatesRequest_()
    : pitch_rate(0.0)
    , roll_rate(0.0)
    , yaw_rate(0.0)
    , thrust(0.0)
    , auto_arm(false)  {
    }
  SetRatesRequest_(const ContainerAllocator& _alloc)
    : pitch_rate(0.0)
    , roll_rate(0.0)
    , yaw_rate(0.0)
    , thrust(0.0)
    , auto_arm(false)  {
  (void)_alloc;
    }



   typedef float _pitch_rate_type;
  _pitch_rate_type pitch_rate;

   typedef float _roll_rate_type;
  _roll_rate_type roll_rate;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef float _thrust_type;
  _thrust_type thrust;

   typedef uint8_t _auto_arm_type;
  _auto_arm_type auto_arm;





  typedef boost::shared_ptr< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRatesRequest_

typedef ::lorett_c4s::SetRatesRequest_<std::allocator<void> > SetRatesRequest;

typedef boost::shared_ptr< ::lorett_c4s::SetRatesRequest > SetRatesRequestPtr;
typedef boost::shared_ptr< ::lorett_c4s::SetRatesRequest const> SetRatesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lorett_c4s::SetRatesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lorett_c4s::SetRatesRequest_<ContainerAllocator1> & lhs, const ::lorett_c4s::SetRatesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pitch_rate == rhs.pitch_rate &&
    lhs.roll_rate == rhs.roll_rate &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.thrust == rhs.thrust &&
    lhs.auto_arm == rhs.auto_arm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lorett_c4s::SetRatesRequest_<ContainerAllocator1> & lhs, const ::lorett_c4s::SetRatesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lorett_c4s

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af3af5eb1fdd1e1bcaa59b13f3881fdb";
  }

  static const char* value(const ::lorett_c4s::SetRatesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf3af5eb1fdd1e1bULL;
  static const uint64_t static_value2 = 0xcaa59b13f3881fdbULL;
};

template<class ContainerAllocator>
struct DataType< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lorett_c4s/SetRatesRequest";
  }

  static const char* value(const ::lorett_c4s::SetRatesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pitch_rate\n"
"float32 roll_rate\n"
"float32 yaw_rate\n"
"float32 thrust\n"
"bool auto_arm\n"
;
  }

  static const char* value(const ::lorett_c4s::SetRatesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch_rate);
      stream.next(m.roll_rate);
      stream.next(m.yaw_rate);
      stream.next(m.thrust);
      stream.next(m.auto_arm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRatesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lorett_c4s::SetRatesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lorett_c4s::SetRatesRequest_<ContainerAllocator>& v)
  {
    s << indent << "pitch_rate: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_rate);
    s << indent << "roll_rate: ";
    Printer<float>::stream(s, indent + "  ", v.roll_rate);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "thrust: ";
    Printer<float>::stream(s, indent + "  ", v.thrust);
    s << indent << "auto_arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_arm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LORETT_C4S_MESSAGE_SETRATESREQUEST_H
