// Generated by gencpp from file lorett_c4s/SetVelocityRequest.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_SETVELOCITYREQUEST_H
#define LORETT_C4S_MESSAGE_SETVELOCITYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lorett_c4s
{
template <class ContainerAllocator>
struct SetVelocityRequest_
{
  typedef SetVelocityRequest_<ContainerAllocator> Type;

  SetVelocityRequest_()
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yaw(0.0)
    , yaw_rate(0.0)
    , frame_id()
    , auto_arm(false)  {
    }
  SetVelocityRequest_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yaw(0.0)
    , yaw_rate(0.0)
    , frame_id(_alloc)
    , auto_arm(false)  {
  (void)_alloc;
    }



   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _vz_type;
  _vz_type vz;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef uint8_t _auto_arm_type;
  _auto_arm_type auto_arm;





  typedef boost::shared_ptr< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelocityRequest_

typedef ::lorett_c4s::SetVelocityRequest_<std::allocator<void> > SetVelocityRequest;

typedef boost::shared_ptr< ::lorett_c4s::SetVelocityRequest > SetVelocityRequestPtr;
typedef boost::shared_ptr< ::lorett_c4s::SetVelocityRequest const> SetVelocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lorett_c4s::SetVelocityRequest_<ContainerAllocator1> & lhs, const ::lorett_c4s::SetVelocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz &&
    lhs.yaw == rhs.yaw &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.frame_id == rhs.frame_id &&
    lhs.auto_arm == rhs.auto_arm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lorett_c4s::SetVelocityRequest_<ContainerAllocator1> & lhs, const ::lorett_c4s::SetVelocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lorett_c4s

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1c44d548e06dc3c3d2d5e88ecd0aebf";
  }

  static const char* value(const ::lorett_c4s::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1c44d548e06dc3cULL;
  static const uint64_t static_value2 = 0x3d2d5e88ecd0aebfULL;
};

template<class ContainerAllocator>
struct DataType< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lorett_c4s/SetVelocityRequest";
  }

  static const char* value(const ::lorett_c4s::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vx\n"
"float32 vy\n"
"float32 vz\n"
"float32 yaw\n"
"float32 yaw_rate\n"
"string frame_id\n"
"bool auto_arm\n"
;
  }

  static const char* value(const ::lorett_c4s::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.yaw);
      stream.next(m.yaw_rate);
      stream.next(m.frame_id);
      stream.next(m.auto_arm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVelocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lorett_c4s::SetVelocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lorett_c4s::SetVelocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<float>::stream(s, indent + "  ", v.vz);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    s << indent << "auto_arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_arm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LORETT_C4S_MESSAGE_SETVELOCITYREQUEST_H
