// Generated by gencpp from file lorett_c4s/takeoff.msg
// DO NOT EDIT!


#ifndef LORETT_C4S_MESSAGE_TAKEOFF_H
#define LORETT_C4S_MESSAGE_TAKEOFF_H

#include <ros/service_traits.h>


#include <lorett_c4s/takeoffRequest.h>
#include <lorett_c4s/takeoffResponse.h>


namespace lorett_c4s
{

struct takeoff
{

typedef takeoffRequest Request;
typedef takeoffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct takeoff
} // namespace lorett_c4s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lorett_c4s::takeoff > {
  static const char* value()
  {
    return "8a2a35dd048474b9eb06bee7e7e286df";
  }

  static const char* value(const ::lorett_c4s::takeoff&) { return value(); }
};

template<>
struct DataType< ::lorett_c4s::takeoff > {
  static const char* value()
  {
    return "lorett_c4s/takeoff";
  }

  static const char* value(const ::lorett_c4s::takeoff&) { return value(); }
};


// service_traits::MD5Sum< ::lorett_c4s::takeoffRequest> should match
// service_traits::MD5Sum< ::lorett_c4s::takeoff >
template<>
struct MD5Sum< ::lorett_c4s::takeoffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::takeoff >::value();
  }
  static const char* value(const ::lorett_c4s::takeoffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::takeoffRequest> should match
// service_traits::DataType< ::lorett_c4s::takeoff >
template<>
struct DataType< ::lorett_c4s::takeoffRequest>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::takeoff >::value();
  }
  static const char* value(const ::lorett_c4s::takeoffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lorett_c4s::takeoffResponse> should match
// service_traits::MD5Sum< ::lorett_c4s::takeoff >
template<>
struct MD5Sum< ::lorett_c4s::takeoffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lorett_c4s::takeoff >::value();
  }
  static const char* value(const ::lorett_c4s::takeoffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lorett_c4s::takeoffResponse> should match
// service_traits::DataType< ::lorett_c4s::takeoff >
template<>
struct DataType< ::lorett_c4s::takeoffResponse>
{
  static const char* value()
  {
    return DataType< ::lorett_c4s::takeoff >::value();
  }
  static const char* value(const ::lorett_c4s::takeoffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LORETT_C4S_MESSAGE_TAKEOFF_H
